apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-svc
spec:
  type: NodePort
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ .Values.frontend.name }}