#frontend
frontend:
  name: frontend
  replicaCount: 1
  image: shreybatra/sample-frontend
  service: 
    port: 5173
    nodePort: 31000

#backend
backend:
  name: backend
  replicaCount: 1
  image: shreybatra/sample-backend
  service: 
    port: 8000

#db
redis: 
  name: redis
  replicaCount: 1
  image: redis
  service: 
    port: 6379
